add README file
weeve-modules/data-converter pull request #2
Opened 2022-08-24 12:14 UTC by GhasBarbouchi

remove comments and add the READme file

2022-08-24 13:33 UTC, europaul requested changes
also:
1. some of the conversion functions in converter.py only return True, but not False
2. I think you misspelled ieee754 for ieee547 in some cases

2022-08-24 13:33 UTC, europaul commented on test/assets/input.json
> +            }
better indentation would be nice

2022-08-24 13:33 UTC, europaul commented on src/module/converter.py
>  from functools import reduce  # forward compatibility for Python 3
I think the comment is meaningless since we are only using python 3

2022-08-24 13:33 UTC, europaul commented on test/assets/input.json
> +            }
also, what is the point of this change? you don't change the expected output or the test accordingly so the tests fail

2022-08-24 13:33 UTC, europaul commented on src/module/module.py
> +        data_to_convert = detect_input(getenv('INPUT_KEY'),received_data)
could you please format all the python files with "Right click anywhere in the file -> Format Document"

2022-08-24 13:33 UTC, europaul commented on src/module/module.py
> +        setInDict(received_data,getenv('INPUT_KEY').split('.'),any_conversion(conversion,data_to_convert))
please decide for either snake_case or camelCase and stick with it, don't mix them

2022-08-24 13:33 UTC, europaul commented on src/module/module.py
>              any_conversion(conversion,data_to_convert)
this line appears to do nothing

2022-08-24 13:33 UTC, europaul commented on src/module/module.py
> +        setInDict(received_data,getenv('INPUT_KEY').split('.'),any_conversion(conversion,data_to_convert))
also this function needs some documentation or a comment or better naming explaining what it does. took me a while to figure that out

2022-08-24 13:33 UTC, europaul commented on README.md
> +| name         | data converter                                                   |
```suggestion
| name         | Data Converter                                                   |
```

2022-08-24 13:33 UTC, europaul commented on README.md
> +- [data converter](#data-converter)
please search through the whole directory for `boilerplate` and replace it with the name of the module

2022-08-24 15:23 UTC, europaul commented on src/module/converter.py
>      if type(value) == str:
and if it is not string? same goes for some other functions

2022-08-24 15:23 UTC, europaul commented on test/assets/input.json
> -            "age": 41
why remove it? it will make the tests fail

2022-08-24 15:23 UTC, europaul commented on src/module/module.py
> +        # set_in_dict update the input dictionary (json) with the new value after the conversation
```suggestion
        # update the input dictionary (json) with the new value after the conversion
```

2022-08-24 15:23 UTC, europaul commented on src/module/module.py
>              any_conversion(conversion,data_to_convert)
I was not talking about `print` but about `any_conversion(conversion, data_to_convert)`

2022-08-24 15:26 UTC, GhasBarbouchi commented on src/module/module.py
>              any_conversion(conversion,data_to_convert)
any_conversion is the function convert data_to_convert based on conversion

2022-08-24 15:28 UTC, europaul commented on src/module/module.py
>              any_conversion(conversion,data_to_convert)
but you don't save the result anywhere and call the same function again in the next line

2022-08-24 15:35 UTC, GhasBarbouchi commented on src/module/converter.py
>      if type(value) == str:
if it is not string it will return false
if it is a string return true else return false anyway

2022-08-24 15:39 UTC, europaul commented on src/module/converter.py
>      if type(value) == str:
ok, I think you don't know this about GitHub, but the comment always refers to the line showed last on the screen. Sometimes it's the last several lines. All the lines above that are displayed just for context. So in this case I'm talking about the line 49

2022-08-24 15:41 UTC, GhasBarbouchi commented on src/module/module.py
>              any_conversion(conversion,data_to_convert)
but that line is unnecessary because the function is called in the next line.

2022-08-24 16:21 UTC, europaul commented on src/module/converter.py
>      if type(value) == str:
now the lines 39 and 53 are obsolete

2022-08-24 16:24 UTC, europaul commented on test/assets/input.json
> -            "age": 41
the tests still fail. either reverse everything test-related to the way it was in the boilerplate, so that is clear that you didn't touch the tests; or fix them

2022-08-24 16:35 UTC, GhasBarbouchi commented on test/assets/input.json
> -            "age": 41
ok

2022-08-25 09:55 UTC, europaul approved these changes

2022-08-25 09:57 UTC, merged